### ISSUE TITLE
Quick translation needed

### ISSUE THREAD

**Issue by ManOnDaMoon** [omeka-s-themes/foundation-s#16]
Hello!

On the following lines, the text needs to be fed to the translator plugin:

https://github.com/omeka-s-themes/foundation-s/blob/98cdb8f862121d094dddb50075c6888f6af7cbe7/view/omeka/site/item/browse.phtml#L56

https://github.com/omeka-s-themes/foundation-s/blob/98cdb8f862121d094dddb50075c6888f6af7cbe7/view/omeka/site/item-set/browse.phtml#L22

Have a nice day

Laurent

**Comment by kimisgold** [comment]
"Options" works nicely here. Thank you!
