### ISSUE TITLE
Linked resources thumbnails lose aspect ratio

### ISSUE THREAD

**Issue by ManOnDaMoon** [omeka-s-themes/foundation-s#17]
Hello

On an item show page, linked resources listed in the table have square thumbnails that are a little bit squished down.

Here is an example using the default stylesheet:

<img width="781" alt="Capture d’écran 2020-10-14 à 11 39 24" src="https://user-images.githubusercontent.com/3284234/95971784-f1450f80-0e11-11eb-9450-60c423171e87.png">

Thanks in advance and have a nice day

Laurent

**Comment by ManOnDaMoon** [comment]
A little bit more details because this seems to be browser specific:
- happens using Safari on OSX and iOS. Thumbnails look OK using Chrome.
- happens also to thumbnails as linked resource properties

**Comment by kimisgold** [comment]
@ManOnDaMoon Good catch! Thank you for this.
