### ISSUE TITLE
Linked resources pagination issue

### ISSUE THREAD

**Issue by ManOnDaMoon** [omeka-s-themes/foundation-s#20]
Hello,

Linked resources pagination form has a lot of space around it, but the text is still narrowed down:
<img width="407" alt="Capture d’écran 2020-10-17 à 19 38 31" src="https://user-images.githubusercontent.com/3284234/96349503-75b4be00-10b0-11eb-90cd-741746a10e06.png">
It happens in both Chrome and Safari.

I'm a little bit confused about how to fix this.

Thanks in advance.

Laurent Thomas

**Comment by kimisgold** [comment]
I've pushed some style changes to better position the pagination on the linked resources list. Let me know if this feels better to you!

**Comment by ManOnDaMoon** [comment]
Thanks a lot, that's much better now!
