### ISSUE TITLE
Stylesheet toggle does not work

### ISSUE THREAD

**Issue by lukask99** [omeka-s-themes/foundation-s#34]
Version 1.1.0 for omeka-s version 3.0.2: stylesheet toggle does not work. After selecting a different stylesheet and hitting save, the selection reverts to "default", and the default.css is used.

**Comment by kimisgold** [comment]
Hi, sorry for the delay in responding. I'm having trouble reproducing this on my own install. Do you have a live site I could look at? Also, do any of the other theme settings currently work for you?

**Comment by kimisgold** [comment]
That's pretty odd. Can you switch to another configurable theme to see if you're able to save settings in it?

**Comment by lukask99** [comment]
Other themes save the settings indeed.

**Comment by zerocrates** [comment]
If you have another _site_ within the S install, or if you could make one just for testing, does it have the same problem?

**Comment by lukask99** [comment]
Good point! No, I just created a new site Test, and there it works like expected. So I should now just move my old site to a new one and see if that helps, I guess. Thanks

**Comment by lukask99** [comment]
I created my site by exporting and importing, while upgrading to the latest omeka-s version, maybe something went wrong there?
