### ISSUE TITLE
Test banner image feature

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/foundation-s#38]
There is now a theme setting that allows users to select a banner image to appear across site views. In additional settings, they can control:

* the maximum height of the banner for both mobile and desktop widths
* whether to match the width to the content or window
* where to position the image within the banner container when the container ratio has a much greater width than height

This is on the `master` branch and should be tested on desktop and mobile browsers.

**Comment by sharonmleon** [comment]
Another theme settings element for you to test, @katknow

**Comment by katknow** [comment]
This works well across browsers on both desktop and mobile devices.
