### ISSUE TITLE
Value language labels

### ISSUE THREAD

**Issue by gdostal** [omeka-s-themes/foundation-s#39]
The theme does not seem to honor the core site setting: **Show language labels for values**

Language labels are always shown using foundation-s theme regardless of how the above is set. Omeka default theme does honor this setting, toggling the display of the language labels.

This seems to be related to this theme's override of /view/common/resource-values.phtml. I was able to resolve the issue by merging Omeka core's resrouce-values.phtml with foundation-s'. [Example here.](https://local-history.tplibrary.org/omeka-s/s/Pamphlet/item/17)

How can I best help? Contribute a PR, or simply paste in my code below.

**Comment by kimisgold** [comment]
Thanks for reporting this, as well as your patience waiting for resolution. I'm updating the resource value override, and the fix should be available in the next release.
