### ISSUE TITLE
Faceted browse table not loading

### ISSUE THREAD

**Issue by sharonmleon** [omeka-s-themes/foundation-s#42]
I seem to have broken the rendering of the faceted browse table on Foundations. (It's just not appearing at all.) I've got the latest pull of both the module and the theme. 

Source map error: Error: request failed with status 404
Resource URL: http://6floors.org/workspace/omeka-s/themes/foundation-s/asset/vendor/foundation/foundation.min.js?v=1.2.2
Source Map URL: foundation.min.js.map

**Comment by kimisgold** [comment]
[Just pushed a fix here.](https://github.com/omeka-s-themes/foundation-s/commit/f3cbcac2a9f0dd1b2149d95041127fcebb63386c) Could you see if this fixes it for you?

**Comment by sharonmleon** [comment]
Yep. That did it.
