### ISSUE TITLE
Test configurable page blocks

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/foundation-s#46]
This is the theme-specific issue for omeka/omeka-s#1859. Please test this using the latest version of Omeka S on the `develop` branch.

Foundation now supports configurable resource page blocks. On a site's theme settings panel, select Foundation's "Configure resource pages" button. Test that blocks can be reordered, removed, and readded on the show views of items, media, and item sets. 

Foundation has four block regions, all of which can coexist with each other.

* **Main (full-width)**: This sits above all other regions and takes up the full content width of the page.
* **Main (with sidebar)**: This sits below the full-width main region and inline with either or both sidebar regions. If it is the only populated region, it only takes up partial content width.
* **Left sidebar**: This sits left inline with the main with sidebar region.
* **Right sidebar**: This sits to the right inline with the main with sidebar region.

**Comment by katknow** [comment]
This seems to be working as described.
